### ISSUE TITLE
Cannot use foundation Combobox when using Typescript ^4.0

### ISSUE THREAD

**Issue by paucortescosta** [microsoft/fast#4435]
When updating to @microsoft/fast-foundation v1.15.1, several build errors popped up on some of our modules:

`error TS2611: 'options' is defined as a property in class 'FormAssociatedCombobox', but is overridden here in 'Combobox' as an accessor.`

To repro the issue just consume the latest foundation bits from a project using typescript +v4

**Comment by chrisdholt** [comment]
Thanks @paucortescosta - appears to be caused by https://github.com/microsoft/TypeScript/pull/37894. 

We can start with an investigation as to whether we can refactor. It appears there may be a fix in the works on the TS side to allow for certain cases and scenarios.
